POST http://localhost:5267/arts
Content-Type: application/json

{
    "title": "Butterfly Parade",
    "description": "Uma mulher loira com cabelos tingidos em verde - a personagem 'Jolyne' da obra JJBA - com uma peça de roupa de borboleta",
    "publishDate": "2025-04-08",
    "artistName": "Igor Ribeiro",
    "artistSocial": "@Artigor_",
    "tags": [
        "fanart",
        "digital art",
        "half body",
        "jolyne"
    ],
    "type": [
        "illustration"
    ]
}