@id=32eef6f0-2b34-414a-b5a3-d3ab6c8ff562
PUT http://localhost:5267/arts/{{id}}
Content-Type: application/json

{
    "title": "Buttesdfgfrfly Parade",
    "description": "Uma mulher loira com cabelos tingidos em verde - a personagem 'Jolyne' da obra JJBA - com uma peça de roupa de borboleta",
    "publishDate": "2025-04-08",
    "artistName": "Igor Ribeiro",
    "artistSocial": "@Artigor_",
    "tags": [
        "fanart",
        "digital art",
        "half body",
        "jolyne"
    ],
    "type": [
        "illustration"
    ]
}